CREATE DATABASE IF NOT EXISTS medical_tracker;
USE medical_tracker;

CREATE TABLE IF NOT EXISTS quick_symptoms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  symptom VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  query TEXT NOT NULL,
  when_ts DATETIME DEFAULT CURRENT_TIMESTAMP,
  top TEXT
);
